all: traditional linear_probe

traditional:
	g++ -Wwrite-strings -Werror -Wall -o obj64/traditional traditional.cpp

linear_probe:
	g++ -Wwrite-strings -Werror -Wall -o obj64/linear_probe linear_probe.cpp

clean:
	rm obj64/*
